BATCH_SIZE: 64
COUNT: False
IMAGE_MODEL: /mnt/data/users/apodtikhov/vqa/boxes/
READ: /mnt/data/users/apodtikhov/vqa/extracted_texts/
LR_BASE: 0.0001
LR_DECAY_LIST:
- 10
- 12
LR_DECAY_R: 0.2
MAX_EPOCH: 13
OPT_BETAS: !!python/tuple
- 0.9
- 0.98
OPT_EPS: 1.0e-09
QUES_MODEL: /mnt/data/users/apodtikhov/vqa/albert_base/
dropout_rate: 0.1
fc_size: 2048
flat_mlp_size: 512
flat_out_size: 1024
hidden_size: 512
hidden_size_head: 64
img_feat_pad_size: 100
img_feat_size: 2048
max_token: 36
model_log: /mnt/data/users/apodtikhov/vqa/models/reading/log123456.json
model_pth: /mnt/data/users/apodtikhov/vqa/models/reading/model123456.pth
multi_head: 8
num_layers: 6
word_embedding_size: 4096
num_to_read: 14
